=== Xhinen/HTML/Clases/10clase2609_xml/casasrurales.dtd
<!ELEMENT casas_rurales (casa+)>
<!ELEMENT casa (direccion, descripcion?, estado, (tamanio | hectareas), disponible)>
<!ATTLIST casa id ID #REQUIRED>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT estado (#PCDATA)>
<!ELEMENT tamanio (#PCDATA)>
<!ELEMENT disponible (#PCDATA)>
<!ELEMENT hectareas (#PCDATA)> <!-- Se puede utilizar EMPTY (sin paréntesis) para declarar un datos vacío -->

=== Xhinen/HTML/Clases/10clase2609_xml/casasrurales.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE casas_rurales SYSTEM "casasrurales.dtd">
<casas_rurales>
    <casa id="A1">
        <direccion></direccion>
        <descripcion></descripcion>
        <estado></estado>
        <tamanio></tamanio>
        <disponible></disponible>
    </casa>
    <casa id="A2">
        <direccion></direccion>
        <descripcion></descripcion>
        <estado></estado>
        <hectareas></hectareas>
        <disponible></disponible>
    </casa>
</casas_rurales>
