=== Xhinen/HTML/Clases/10clase2609_xml/factura.dtd
<!-- Ejercicio 3: Factura (DTD externo)

Crea un XML de factura con un DTD externo factura.dtd.

Requisitos:

Raíz: <factura>

Estructura: factura(cabecera, lineas, totales)

<cabecera>: contiene <cliente>, <nif>, <fecha>

<lineas>: contiene una o más <linea> con <producto>, 
<cantidad>, <precioUnitario>

<totales>: contiene <subtotal>, <iva>, <total>

Atributos: cantidad y precioUnitario 
deben ser de tipo CDATA

Define en el DTD una entidad general para el 
porcentaje de IVA (por ejemplo 21) y úsala en el XML; -->

<!ELEMENT factura (cabecera, lineas, totales)>
<!ELEMENT cabecera (cliente, nif, fecha)>
<!ELEMENT cliente (#PCDATA)>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT lineas (linea+)>
<!ELEMENT linea (producto, cantidad, precioUnitario)>
<!ELEMENT producto (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precioUnitario (#PCDATA)>
<!ELEMENT totales (subtotal, iva, total)>
<!ELEMENT subtotal (#PCDATA)>
<!ELEMENT iva (#PCDATA)>
<!ELEMENT total (#PCDATA)>

=== Xhinen/HTML/Clases/10clase2609_xml/ejercicio2factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "factura.dtd">
<!-- Ejercicio 3: Factura (DTD externo)

Crea un XML de factura con un DTD externo factura.dtd.

Requisitos:

Raíz: <factura>

Estructura: factura(cabecera, lineas, totales)

<cabecera>: contiene <cliente>, <nif>, <fecha>

<lineas>: contiene una o más <linea> con <producto>, 
<cantidad>, <precioUnitario>

<totales>: contiene <subtotal>, <iva>, <total>

Atributos: cantidad y precioUnitario 
deben ser de tipo CDATA

Define en el DTD una entidad general para el 
porcentaje de IVA (por ejemplo 21) y úsala en el XML; -->

<factura>
    <cabecera>
        <cliente>Acme S.A.</cliente>
        <nif>A6858584</nif>
        <fecha>2025-09-26</fecha>
    </cabecera>
    <lineas>
        <linea>
            <producto>Teclado mecanico</producto>
            <cantidad>2</cantidad>
            <precioUnitario>59.60</precioUnitario>
        </linea>
    </lineas>
    <totales>
        <subtotal>159.30</subtotal>
        <iva>20.50</iva>
        <total>179.80</total>
    </totales>
</factura>
